 import Footer from "./components/Footer"
 import NavbarActionButtonPreview from "./components/NavbarActionButtonPreview"
 import Home from "./components/Home"
import Bgmi from "./components/Bgmi"
import { BrowserRouter,Routes,Route } from "react-router-dom"
 
 
const App = () => {
  return (
    <>
      <BrowserRouter>
    <NavbarActionButtonPreview/>
    <Routes>
     <Route path="/" element={<Home/>}/>
    <Route path="/bgmi" element={<Bgmi eventname="BGMI" subname="BATTLE ROYAL" price1={'₹3100'} price2={'₹2100'} price3={'₹1100'} rules={['1. Teams consist of four members for squad matches, with solo matches also available.','2. Participants must register for the event, with a 25 rupees per person entry fee, at the C Block venue.','3. Matches are played on the Erangel map.', '4. Emulator players are not allowed; all participants must use mobile devices.','5. Participants must occupy their assigned seats during the event.','6. Disqualification for using unauthorized software or cheats with no entry fee refund.','7. Eliminated squad teams move to the seminar hall of C Block.','8. Prizes are awarded for both squad and solo matches; details in event announcement.','9. Fair play according to BGMIs in-game rules, with match schedule and rules provided by organizers.','10. Players follow organizer instructions for seating at the venue.']} winningconditions={["In squad matches, the winning condition is typically the last surviving team. The squad that has at least one member alive while all other teams are eliminated is declared the winner."]}  />}/>
    <Route path="/techtreasure" element={<Bgmi eventname="TECH" subname="TREASURE"  price1={'₹1100'} price2={'₹750'} price3={'₹500'}  rules={["1. Maximum 2 students are allowed in a team.","2. Unregisterd students are not allowed to help any team or any member. ","3. Teams can’t help another team to get clues. ","4. Firstly teams have to solve the clue. ","5. The answer of the clue will help find folder to next clue."]} winningconditions={["1. Within the minimum time got the treasure got 1,2,3 positions respectively.","2. Teams have to submit the treasure at start point." 
    ]}  />}/>
    <Route path="/webreplicarace" element={<Bgmi eventname="WEB" subname="REPLICA RACE"  price1={'₹1100'} price2={'₹750'} price3={'₹500'}  rules={["1. No internet connection will be provided. ","2. Notepad will be used as a text editor. ","3. If anyone seems to help anyone in the participants, he or she will be disqualified without any warning. ","4. Only one person will be allowed in one team."]} winningconditions={["Whoever has prepared the best replica of the given website in the given time will be rewarded." 
    ]}  />}/>
    <Route path="/sudokusaga" element={<Bgmi eventname="SUDOKU" subname="SAGA"  price1={'₹1100'} price2={'750'} price3={'₹500'}  rules={["● Round 1: Simple Sudoku (Preliminary Round): ","1. Participants must be present at the specified venue on time to participate. ","2. Participants will be provided with a Sudoku puzzles. ","3. The preliminary round will last for 15 minutes. ","4. Participants are required to solve Sudoku puzzles as possible within the given time. ","5. The top 20 participants who solve the puzzles accurately in the given time will be eligible to the next round. ","6. Usage of any external aids or electronic devices (unless specified) is strictly prohibited. ","7. Participants found violating the rules will be disqualified. ","● Round 2: Samurai Sudoku ","1. Participants will be provided with Samurai Sudoku puzzles to solve. ","2. The final round will have a specific time limit(40min) for solving the Samurai Sudoku puzzle. ","3. Participants must solve the Samurai Sudoku puzzle accurately within the given time. ","4. The participant who correctly solves the Samurai Sudoku puzzle in the shortest time will be declared the winner of the event. "]} winningconditions={["The participant who correctly solves the Samurai Sudoku puzzle in the shortest time will be declared the winner of the event." 
    ]}  />}/>
    <Route path="/unscramblethesource" element={<Bgmi eventname="UNSCRAMBLE" subname="THE SOURCE"  price1={'₹1100'} price2={'₹750'} price3={'₹500'}  rules={["1. Enrollment is necessary. ","2.Participation certificate will be provided  to only those participants who will clear level 1.","3. All Electronic Gadgets are restricted."]} winningconditions={["Whoever will complete the given task in  least time will win." 
    ]}  />}/>
    <Route path="/codersbattleground" element={<Bgmi eventname="CODERS" subname="BATTLE GROUND"  price1={'₹1100'} price2={'₹750'} price3={'₹500'}  rules={["1. Single Participant is allowed (No Team). "," 2. Candidates must have a HACKERRANK account for participating in this contest. ","3. Report at Venue at least 15 mins prior for getting clear instructions about both round and rules. ","4. One Participant can’t help another participant to get clues , if found doing the same then both will be disqualified. ","5. Electronic Gadgets such as smartwatches, smartphones ,etc. are not allowed inside the lab during the contest.(Mobile Phones are allowed for preliminary Round after Pre. Round Mobiles Phones Will be submitted by the Organizers.) ","6. If anyone found cheating or using smart-way to cheat will be disqualified."]} winningconditions={["1. Candidates will be given 15 MCQ’s for the first round and Candidates as per scores will be selected for the final round. " ,"2. Candidates will be given 20 Coding Questions and candidate who will solve the maximum Questions with appropriate expected output in least timing will be choosen as winners. ","3. Participant Solved highest Coding answers in least time will be first and next would be second and next one would be third."
    ]}  />}/>
    <Route path="/typingthunder" element={<Bgmi eventname="TYPING" subname="THUNDER" price1={'₹1100'} price2={'₹750'} price3={'₹500'}   rules={["1. Single Participant is allowed (No Team). ","2. Participants must report to the venue at least 15 minutes prior to receive instructions. ","3. Participants are not allowed to help each other; doing so will result in disqualification. ","4. There will be 3 rounds and the participants who will be selected will go to the next round. ","5. Participants will be provided a time. "]} winningconditions={["1. The participant who will reach to the last round and complete within the time limit will be the winner. ","2. Winners will be judged based on the typing speed and accuracy. " 
    ]}  />}/>
    <Route path="/terroroferror" element={<Bgmi eventname="TERROR" subname="OF ERROR"  price1={'₹1100'} price2={'₹750'} price3={'₹500'}  rules={["1. Student must register individually. ","2. Time limit for this competition is 1 hour. ","3. Elimination round for in-house students may be conducted if required .","4.Participants should be register in hackerrank. ","5. Each participant is required to debug the given program(s) written in C language. ","6. There will be two rounds.","7. Source code with errors will be given and you have to ractify the code . ","8. The basic purpose and expected output of the program will be clearly mentioned in the beginning of the source code within multi-line comments. The code must be debugged in such a way that the basic purpose is served and expected output is produced by the debugged program. ","9. While debugging a program, if errors are introduced in the program, the participant only will have to remove it and no help will be provided by any faculty/staff member. "]} winningconditions={["The participant who correctly solves the Debugging challenges in the shortest time will be declared the winner of the event." 
    ]}  />}/>
    <Route path="/designshowdown" element={<Bgmi eventname="DESIGN" subname="SHOWDOWN"  price1={'₹1100'} price2={'₹750'} price3={'₹500'}  rules={["1. Single Participant is allowed (No Team). ","2. Participants must report to the venue at least 15 minutes prior to receive instructions. ","3. Participants are not allowed to help each other; doing so will result in disqualification. ","4. There will be 3 rounds and the participants who will be selected will go to the next round. ","5. Participants will be provided a time."]} winningconditions={["1. The participant who will reach to the last round and complete within the time limit will be the winner. ","2. Winners will be judged based on the typing speed and accuracy." 
    ]}  />}/>
    <Route path="/mememadness" element={<Bgmi eventname="MEME" subname="MADNESS"  price1={'₹1100'} price2={'₹750'} price3={'₹500'}  rules={["● Round 1: (Preliminary Round): ","1. Participants must be present at the specified venue on time to participate. ","2. Meme shouldn&#39;t be related to any religion or must not use abusive language. ","3. Topics will be provided at the time of event. ","4. Participants must create memes related to the given topics. ","5. The preliminary round will last for 20 minutes. ","6. Participants are typically required to create their own original memes rather than using pre-existing memes. Plagiarism or the use of copyrighted material may be prohibited. ","7. The top 5 participants who made the funny meme in the given time will be eligible to the next round. ","8. Criteria for judging include creativity, humor, relevance to the theme, and overall impact. ","9. Participants found violating the rules will be disqualified. ","● Round 2: Final round ","1. All participants will be provided a new topic. ","2. The final round will have a specific time limit(30min) for thinking and making meme. ","3. Content should not be controversial. ","4. The participant who made the funniest meme in the given time will be declared the winner of the event. "]} winningconditions={["The participant who made the funniest meme will be declared the winner of the event. " 
    ]}  />}/>
    <Route path="/technicalpresentation" element={<Bgmi eventname="TECHNICAL" subname="PRESENTATION"  price1={'₹1100'} price2={'₹750'} price3={'₹500'}  rules={["1. Single Participant is allowed (No Team). ","2. Participants must report to the venue at least 15 minutes prior to receive instructions. ","3. Participants are not allowed to help each other; doing so will result in disqualification. ","4. Participants are required to work solely on the basis of their knowledge. ","5. Participants must bring their ppt and equipment. ","6. Participants ppt Format should be like:-","(i) Title,Abstract and Keyword ","(ii) Intro,Methodology and Literature Survey ","(iii) Result,Conclusion and Reference. ","7. Judges&#39; decision will be final. ","8. The organizers reserve the right to change any rule."]} winningconditions={["The participant who explained their ppt in proper format and correctly will be declared the winner of the event. " 
    ]}  />}/>
    <Route path="/quiz" element={<Bgmi eventname="QUIZ" subname="QUEST" price1={'₹1100'} price2={'₹750'} price3={'₹500'}   rules={["1. •	Only team entries are allowed , and team shall consist of  maximum three persons and minimum 1 person.","2. The descision of the quiz-master will be final and will not be subjected to change.","3. The participants shall not be allowed to use mobile  or any other electronic instrument.","4. The questions will be In the form of Multiple choice, true/false statement , specific answer question etc.","5. Replacement of any participant of a team is not allowed after registration.","6. This quiz is based on technological questions.","7.	Participants must carry their ID card."]} winningconditions={["Winners will be based on points ." 
    ]}  />}/>
    <Route path="/innovision" element={<Bgmi eventname="Mini" subname="Project" price1={'₹1100'} price2={'₹750'} price3={'₹500'}   rules={["1. Student can pair up or participate solo.","2. Unregistered students are not allowed to help any team or any member.","3. Teams can’t help another team.","4. Mobile phones and use of internet is not allowed.","5. Participate can run there project only on turbo c."]} winningconditions={["1. Team with best project and presentation of their project very well will be the winner. ","2. The project code should be optimized and that should execute well." 
    ]}  />}/>
  </Routes> 
    <Footer/>   
      </BrowserRouter>
    </>
    
    )
}

export default App